name: PHPStan

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:0b62ed1ee1fecb7e922e5e31028b21bd7221af391c2302832f31791746ed0a2a
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPStan
        uses: docker://ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:0b62ed1ee1fecb7e922e5e31028b21bd7221af391c2302832f31791746ed0a2a
        with:
          args: analyze --error-format=table /github/workspace
