name: PHPStan

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:43a77b6b677dc282763ee41504f0f37fd91d2bfc511050b0af66422b129fd1fc
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Composer
        run: composer install

      - name: PHPStan
        uses: docker://ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:43a77b6b677dc282763ee41504f0f37fd91d2bfc511050b0af66422b129fd1fc
        with:
          args: analyze --error-format=table /github/workspace
