name: PHPStan

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:b62620ecad71a4c7777be5c51f6ed185461461da947ac92fe1d78702a310a8fb
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPStan
        uses: docker://ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:b62620ecad71a4c7777be5c51f6ed185461461da947ac92fe1d78702a310a8fb
        with:
          args: analyze --error-format=table /github/workspace
