name: PHPUnit

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:578ad645c10372487c43919f3179dcd1de2feb965db7ab5c45ef75525bdcd320
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPUnit
        run: composer test
