name: PHPUnit

on:
  pull_request:
  merge_group:
  push:
    branches:
      - 'renovate/**'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sgoettsch/docker-phpstan:latest-php8.2@sha256:3f0897b87a25777775f1f588929e52d6867ca989fad316d1b94e91f88fb94c5f
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Composer
        run: composer install

      - name: PHPUnit
        run: composer test
